config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { registrations: "registrations"}
  resources :forms
  get 'site/home'

  get 'site/gracias'

  root 'forms#new'

    get 'dashboard' => 'forms#dashboard'
    get 'results' => 'forms#results'
	get 'responder' => 'forms#new'
	get 'gracias' => 'site#gracias'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/form.rb
class Form < ActiveRecord::Base
	validates :email, presence: true, uniqueness: true
	validates :nombre, :apellido, :ciudad, :pais, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    
  require 'csv'
    
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :set_form, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, except: [:new, :create]

  # GET /forms
  # GET /forms.json

#  def index
#    @forms = Form.all
#  end

def index
  @forms = Form.all
  respond_to do |format|
    format.html
    format.csv do
      headers['Content-Disposition'] = "attachment; filename=\"form-list.csv\""
      headers['Content-Type'] ||= 'text/csv'
    end
  end
end

  # GET /forms/1
  # GET /forms/1.json
  def show
  end

  # GET /forms/new
  def new
    @form = Form.new
  end

  # GET /forms/1/edit
  def edit
  end

  # POST /forms
  # POST /forms.json
  def create
    @form = Form.new(form_params)

    respond_to do |format|
      if @form.save
		format.html { redirect_to gracias_url, notice: 'Tu encuesta fue enviada satisfactoriamente.' }
        format.json { render :show, status: :created, location: @form }
      else
        format.html { render :new }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forms/1
  # PATCH/PUT /forms/1.json
  def update
    respond_to do |format|
      if @form.update(form_params)
		format.html { redirect_to @form, notice: 'La encuesta fue actualizada.' }
        format.json { render :show, status: :ok, location: @form }
      else
        format.html { render :edit }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forms/1
  # DELETE /forms/1.json
  def destroy
    @form.destroy
    respond_to do |format|
	  format.html { redirect_to forms_url, notice: 'La encuesta fue borrada.' }
      format.json { head :no_content }
    end
  end

  def dashboard
    @conteo = Form.count
  end

  def results
    @total = Form.count
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form
      @form = Form.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def form_params
      params.require(:form).permit(:nombre, :apellido, :email, :ciudad, :pais)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  before_action :one_user_registered?, :except => [:edit,:update,:destroy]

  protected

  def one_user_registered?
    if ((Admin.count == 1) & (admin_signed_in?))
      redirect_to root_path
    elsif Admin.count == 1
      redirect_to new_admin_session_path
    end  
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  before_action :authenticate_admin!, only: :home
  def home
  end

  def gracias
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/forms/_form.html.erb
<%= form_for(@form) do |f| %>
  <% if @form.errors.any? %>
    <div id="error_explanation">
      <h2>Oops! Hay errores con tu formulario:</h2>

      <ul>
      <% @form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.text_field :nombre, class: 'form-control', placeholder: "Tu nombre:" %>
  </div>
  <div class="field form-group">
    <%= f.text_field :apellido, class: 'form-control', placeholder: "Tu apellido:" %>
  </div>
  <div class="field form-group">
    <%= f.text_field :email, class: 'form-control', type: 'email', placeholder: "Tu email:" %>
  </div>
  <div class="field form-group">
    <%= f.text_field :ciudad, class: 'form-control', placeholder: "Tu ciudad:" %>
  </div>
  <div class="field form-group">
    <%= f.text_field :pais, class: 'form-control', placeholder: "Tu país:" %>
  </div>
  <div class="actions">
      <%= f.submit 'Enviar encuesta', :class => 'btn btn-lg btn-block btn-primary my-3' %>
  </div>
<% end %>

app/views/forms/dashboard.html.erb
<div class="row">
	<div class="col">
		<h1>Campaña de Firmas: Sin Rodeo</h1>
        <hr>
      <p class="lead">De un vistazo</p>
  </div>
</div>
<div class="row">
	<div class="col-sm-6">
		<div class="panel panel-default">
          <div class="panel-body">
            <h4 class="text-center">¿Cómo vamos?</h4>
            <h1 class="text-center"><%= @conteo %></h1>
            <p class="text-center">encuestas han sido recibidas a la fecha.</p>
          </div>
      </div>
	</div>
	<div class="col-sm-6">
		<div class="panel panel-default">
          <div class="panel-body">
            <h4 class="text-center">Descargar los resultados</p>
            <h1 class="text-center"><%= link_to 'Lista CSV', forms_path(format: :csv), :class => 'btn btn-block btn-primary' %></h1>
            <p class="text-center"><small>Los resultados se descargarán en un archivo CSV que puede importarse y editarse en Excel.</small></p>
          </div>
      </div>
	</div>
</div>
<%#
	# <div class="row">
	# 	<div class="col">
	# 		<div class="panel panel-default">
	#           <div class="panel-body">
	#             <h4 class="text-center">Resultados</h4>
	#             <p class="text-center">Próximamente.</p>
	#           </div>
	#       </div>
	# 	</div>
	# </div>
	%>

app/views/forms/edit.html.erb
<h1>Editing form</h1>

<%= render 'form' %>

<%= link_to 'Show', @form %> |
<%= link_to 'Back', forms_path %>

app/views/forms/export.csv.erb
<%- headers = ['Nombre', 'Apellido', 'Email', 'Ciudad', 'País'] -%>
<%= CSV.generate_line headers %>
<%- @forms.each do |form| -%>
<%= CSV.generate_line([form.nombre, form.apellido, form.email, form.ciudad, form.pais]) -%>
<%- end -%>

app/views/forms/index.csv.erb
<%- headers = ['Nombre', 'Apellido', 'Email', 'Ciudad', 'País'] -%>
<%= CSV.generate_line headers %>
<%- @forms.each do |form| -%>
<%= CSV.generate_line([form.nombre, form.apellido, form.email, form.ciudad, form.pais]) -%>
<%- end -%>

app/views/forms/index.html.erb
<h1>Lista de respuestas</h1>

<%= link_to 'Descargar lista en formato CSV', forms_path(format: :csv), :class => 'btn btn-primary', :role => 'button'  %>

<div class="table-responsive">
<table class="table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Email</th>
      <th>Ciudad</th>
      <th>País</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @forms.each do |form| %>
      <tr>
        <td><%= form.nombre %></td>
        <td><%= form.apellido %></td>
        <td><%= form.email %></td>
        <td><%= form.ciudad %></td>
        <td><%= form.pais %></td>
        <td><%= link_to 'Mostrar', form %></td>
        <td><%= link_to 'Editar', edit_form_path(form) %></td>
        <td><%= link_to 'Borrar', form, method: :delete, data: { confirm: '¿De verdad quieres hacer esto?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'Nueva encuesta', new_form_path,  :class => 'btn btn-default', :role => 'button' %>

app/views/forms/new.html.erb
<div class="row">
	<div class="col">
		<h3 class="sub-header">Nueva Encuesta</h3>
		<%= render 'form' %>
		<% if admin_signed_in? %>
    	<%= link_to 'Volver', forms_path, class: 'btn btn-block btn-default' %>
		<% end %>
	</div>
</div>

app/views/forms/results.html.erb
<div class="row">
	<div class="col-xs-12">
		<h1>Política Animalista y II Censo Vegetariano</h1>
        <hr>
      <p class="lead text-center">Datos demográficos de nuestras <%= @total %> encuestas</p>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <h3>Género</h3>
    </div>
</div>
<div class="row">
	<div class="col-sm-4">
		<div class="panel panel-default">
          <div class="panel-body">
            <h4 class="text-center">Femenino</h4>
            <h1 class="text-center"><%= @niñas %></h1>
          </div>
      </div>
	</div>
	<div class="col-sm-4">
		<div class="panel panel-default">
          <div class="panel-body">
            <h4 class="text-center">Masculino</h4>
            <h1 class="text-center"><%= @niños %></h1>
          </div>
      </div>
	</div>
	<div class="col-sm-4">
		<div class="panel panel-default">
          <div class="panel-body">
            <h4 class="text-center">No Binario</h4>
            <h1 class="text-center"><%= @niñes %></h1>
          </div>
      </div>
	</div>
</div>

<div class="row">
    <div class="col-sm-12">
        <h3>Comunas</h3>
    </div>
</div>
<div class="row">
	<div class="col-sm-12">
        <p><strong>Las 5 comunas</strong> con más encuestas recibidas:</p>
        <div class="table-responsive">
          <table class="table">
            <tbody>
              <% @comunas.each do |comuna,conteo| %>
              <tr>
                <td>
                  <%= comuna %>
                </td>
                <td>
                  <%= conteo %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>    
	</div>
</div>
<div class="row">
	<div class="col-sm-12">
        <p>Tipos de <strong>alimentación</strong> en orden descendiente:</p>
        <div class="table-responsive">
          <table class="table">
            <tbody>
              <% @alim.each do |tipo,conteo| %>
              <tr>
                <td>
                  <%= tipo %>
                </td>
                <td>
                  <%= conteo %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>    
	</div>
</div>

app/views/forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre</strong>
  <%= @form.nombre %>
</p>

<p>
  <strong>Apellido</strong>
  <%= @form.apellido %>
</p>

<p>
  <strong>Mail</strong>
  <%= @form.email %>
</p>

<p>
  <strong>Ciudad</strong>
  <%= @form.ciudad %>
</p>

<p>
  <strong>País</strong>
  <%= @form.pais %>
</p>

<%= link_to 'Edit', edit_form_path(@form) %> |
<%= link_to 'Back', forms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Test: Nuevo formato de formulario - Vegetarianos Hoy</title>
  <!-- Required meta tags always come first -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Typekit -->
  <script src="https://use.typekit.net/wbk4xfe.js"></script>
  <script>try{Typekit.load({ async: true });}catch(e){}</script>

</head>
<body>
  <div class="container">
    <div class="row">
      <div class="col">
        <% if admin_signed_in? %>
        <nav class="navbar navbar-expand-md navbar-light bg-light bg-faded">
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCP2" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <a class="navbar-brand" href="<%= root_path %>">
            <%# image_tag 'logoCP-head.png', :width => 30, :height => 30, :class => "d-inline-block align-top" %>
            Sin Rodeo
          </a>
          <div class="collapse navbar-collapse" id="navbarCP2">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item"><%= link_to 'Un vistazo', dashboard_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to 'Encuesta', new_form_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to 'Detalle', forms_path, class: "nav-link" %></li>
              <li class="nav-item"><%= link_to 'Lista CSV', forms_path(format: :csv), class: "nav-link" %></li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  ⚙️
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <%= link_to 'Portada', root_path, class: "dropdown-item" %>
                    <%= link_to 'Editar perfil', edit_admin_registration_path, class: "dropdown-item", role: "button" %>
                    <%= link_to 'Cerrar Sesión', destroy_admin_session_path, method: :delete, class: "dropdown-item", role: "button" %>
                </div>
              </li>
            </ul>
          </div>
        </nav>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <div><%= notice %></div>
        <div><%= alert %></div>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <%= yield %>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <p class="footer">&copy; 2016 Vegetarianos Chile.</p>
      </div>
    </div>
  </div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-72716662-3', 'auto');
  ga('send', 'pageview');

</script>

</body>
</html>

app/views/site/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/site/form.html.erb
<h1>Pages#form</h1>
<p>Find me in app/views/pages/form.html.erb</p>

app/views/site/gracias.html.erb
<div class="row">
	<div class="col-xs-12">
		<h1 class="text-center">¡Muchas gracias!</h1>
		<hr>
		<h4>Has completado nuestra encuesta. Agradecemos tus respuestas, las cuales nos ayudarán a conocernos mejor. Ahora ya estás participando en el sorteo de una máquina Biomilk para hacer leches vegetales (precio de referencia: $98.000). ¡Mucha suerte!</h4>
		<h4>Puedes cerrar esta ventana.</h4>		
	</div>
</div>

app/views/site/home.html.erb
<div class="row">
	<div class="col-xs-12">
		<h1>Política Animalista y II Censo Vegetariano</h1>
        <hr>
      <p class="lead">De un vistazo</p>
  </div>
</div>
<div class="row">
	<div class="col-sm-4">
		<div class="panel panel-default">
          <div class="panel-body">
            <h4 class="text-center">¿Cómo vamos?</h4>
            <p class="text-center"><em>Próximamente</em></p>
          </div>
      </div>
	</div>
	<div class="col-sm-4">
		<div class="panel panel-default">
          <div class="panel-body">
            <h4 class="text-center">Descargar los resultados</p>
            <h1 class="text-center"><%= link_to 'Lista CSV', forms_path(format: :csv), :class => 'btn btn-block btn-primary' %></h1>
            <p class="text-center"><small>Los resultados se descargarán en un archivo CSV que puede importarse y editarse en Excel.</small></p>
          </div>
      </div>
	</div>
	<div class="col-sm-4">
		<div class="panel panel-default">
          <div class="panel-body">
            <h4 class="text-center">Realizar sorteo</h4>
            <p class="text-center"><em>Próximamente</em></p>
          </div>
      </div>
	</div>
</div>